### ISSUE TITLE
Clean up imports

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#13]
Hi @SenthilCaesar ,

All the scripts have redundant and repeated imports.

For example, see `pipeline/dwi_masking.py`:
```
import os.path
from os import path
```
Not only the duplication exists, but also the above block has been repeated. Similar repetition exists for other libraries as well.

To fix this, please create a new branch `clean-imports` from `remove-ext-dep`, and then make changes in the former. I shall review your changes and merge with `remove-ext-dep`. Please don't edit on `remove-ext-dep` branch.

**Comment by tashrifbillah** [comment]
Do the following:

```bash
git pull origin remove-ext-dep
git checkout -b clean-imports
# correct the scripts
# commit your changes
git push -u origin clean-imports

```

**Comment by tashrifbillah** [comment]
More repetition:

> cd src
```bash
(tf) [tb571@pnl-z840-2 src]$ grep -e "tensorflow" *py
compnet_axial.py:import tensorflow as tf
compnet_axial.py:import tensorflow as tf
compnet_coronal.py:import tensorflow as tf
compnet_coronal.py:import tensorflow as tf
compnet_sagittal.py:import tensorflow as tf
compnet_sagittal.py:import tensorflow as tf

```

**Comment by SenthilCaesar** [comment]
Repeated imports removed and changes pushed to clean-imports branch
