### ISSUE TITLE
Flawed design for binary file

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#14]
The following files are common for all users:

```
axial-binary-dwi
coronal-binary-dwi
sagittal-binary-dwi
```

That means, user A would have to overwrite user B's content, which would result in a permission issue.

Let's meet and talk about fixing all such problems in the software.

**Comment by SenthilCaesar** [comment]
Flawed design for binary file is fixed by added process id

**Comment by tashrifbillah** [comment]
Commit: https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation/commit/eeeafd90a9dedd71fd1bcb7885302759cd7f12e1
