### ISSUE TITLE
I can't download model-folder. ERROR:404

### ISSUE THREAD

**Issue by a1029602653** [pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#19]

**Comment by tashrifbillah** [comment]
Please provide the commands you tried and complete error log.

**Comment by a1029602653** [comment]
wget https://github.com/pnlbwh/Harmonization-Python/releases/download/v0.2/model_folder.tar.gz
--2020-03-15 15:09:22--  https://github.com/pnlbwh/Harmonization-Python/releases/download/v0.2/model_folder.tar.gz
正在解析主机 github.com (github.com)... 13.229.188.59
正在连接 github.com (github.com)|13.229.188.59|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 301 Moved Permanently
位置：https://github.com/pnlbwh/dMRIharmonization/releases/download/v0.2/model_folder.tar.gz [跟随至新的 URL]
--2020-03-15 15:09:24--  https://github.com/pnlbwh/dMRIharmonization/releases/download/v0.2/model_folder.tar.gz
再次使用存在的到 github.com:443 的连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2020-03-15 15:09:25 错误 404：Not Found。

**Comment by tashrifbillah** [comment]
Should be fixed now.
Thanks for pointing out the incorrect URL.
