### ISSUE TITLE
Remove all hard-coded paths

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#3]
Follow up from work group on 1/29/2020

For open-source distribution of the software, all hard-coded paths such as `/rfanfs/...` must be omitted.

See the following search result:

https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation/search?q=%2Frfanfs&unscoped_q=%2Frfanfs

**Comment by tashrifbillah** [comment]
cc: @yrathi @sbouix

**Comment by SenthilCaesar** [comment]
Hard coded paths removed
