### ISSUE TITLE
Uncontrolled multiprocessing is in place in this program!!

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#39]
This block is not connected to `args.cr`:

https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation/blob/8caf97fc6b423d778c0b6b9988f50eb1825b1604/pipeline/dwi_masking.py#L627-L675

https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation/blob/8caf97fc6b423d778c0b6b9988f50eb1825b1604/pipeline/dwi_masking.py#L571

Hence, it spawns as many processes as the number of cases in `caselist.txt`. This will blow out the CPU. It was not discovered so far because [test pipeline](https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation/blob/master/tests/pipeline_test.sh) included in this project has only three cases. Tashrif discovered it while trying to utilize its inherent looping facility over 220 cases. All 220 cases spawned uncontrollably!!

It needs to be fixed using a standard multiprocessing coding e.g. https://github.com/pnlbwh/TBSS/blob/2fb1bc776b07013b450c24057db876486fc4bb2b/lib/tbss_single.py#L112-L121

**Comment by tashrifbillah** [comment]
cc @RyanZurrin

**Comment by RyanZurrin** [comment]
Hello Tashrif,

I can take a look at this and help come up with a fix later this week, maybe tomorrow, if not then Thrusday and Frideay for sure. 

If you fix it before that let make know otherwise I will reach out to you soon.

**Comment by RyanZurrin** [comment]
I have additional concerns besides the spawning of many processes that this script is only set to handle one GPU. If you have a case list of 100 subjects and say the CPU issue is fixed to not use more than nproc at any given time, which is 8 by default, then you will need a very high-performance GPU to handle 8 cases in parallel. I think more changes need to happen that effectivaly assign GPU usage in Round Robbin fashion

**Comment by RyanZurrin** [comment]
`            """
            Enable Multi core Processing for pre processing
            manager provide a way to create data which can be shared between different processes
            """
            with Manager() as manager:
                target_list = manager.list()
                with mp.Pool(processes=args.cr) as pool:
                    for case in case_arr:
                        pool.apply_async(pre_process, (case, target_list))
                    pool.close()
                    pool.join()

                target_list = list(target_list)

                """
                Enable Multi core Processing for ANTS Registration
                manager provide a way to create data which can be shared between different processes
                """
                result = manager.list()

                with mp.Pool(processes=args.cr) as pool:
                    for target in target_list:
                        pool.apply_async(ANTS_rigid_body_trans, (target, result, reference))
                    pool.close()
                    pool.join()

                result = list(result)
                data_n = manager.list()

                with mp.Pool(processes=args.cr) as pool:
                    for transformed_case, _ in result:
                        pool.apply_async(normalize, (transformed_case, args.percentile, data_n))
                    pool.close()
                    pool.join()

                data_n = list(data_n)
`

I have updated the section of code to use a Pool and it is now connected to the -nproc flag which gets saved as args.cr. I have successufully tested with a few subjects setting nproc to 1 and 2 and it would only allow that many processes to spawn at any given time. I will create a pull request with this fix
