### ISSUE TITLE
CNN Masking PA Direction

### ISSUE THREAD

**Issue by kavandeloo97** [pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#49]
Can you confirm if CNN masking can be performed on dwi images in the PA direction (b=0)? 

I seem to get really weird results when running this on PA images - the output is only a single slice in the axial view, and only a single line is visible in coronal/sagittal views.

My understanding is that I would run CNN masking on both the AP and PA dwi images, prior to running fsl_topup_epi_eddy. Although I could run BET for the PA images, using the same method as the AP images is preferred for consistency.

**Comment by tashrifbillah** [comment]
Use https://github.com/pnlbwh/luigi-pnlpipe/blob/1a42995d022c57dd16b4239749573b9910aa5a9c/workflows/hcp_pnl_topup.lsf . fsl_topup_epi_eddy is out of commission.

> the output is only a single slice in the axial view, and only a single line is visible in coronal/sagittal views.

You made some mistake. That's why.

**Comment by kavandeloo97** [comment]
How long has it been out of commission? I used it semi-recently. 

I didn't make a mistake, but will try rerunning again with a new dataset.

**Comment by tashrifbillah** [comment]
Since 2021.

**Comment by kavandeloo97** [comment]
Can you provide more information? Just wondering if the outputs of the data I analyzed using this command are unusable. Thanks!
