### ISSUE TITLE
Which volume is extracted as b0?

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#6]
@SenthilCaesar @suheyla2 

Can you tell me which bvalue is used in extracting b0 image [here](https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation/blob/master/pipeline/preprocessing.py#L129)?

Please see standard PNL way of extracting b0 image [here](https://github.com/pnlbwh/pnlNipype/blob/master/docs/TUTORIAL.md#i-baseline-image) and let me know which one is relevant to this project.

**Comment by suheyla2** [comment]
Dwiextract extracts all bzeros.
Senthil was later taking an average of the b0s.

-ave option with default threshold would work.


________________________________

**Comment by tashrifbillah** [comment]
Fixed by https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation/commit/c18b5f5bc51b955a07e55b52e35f9b5ea0528a0f
