### ISSUE TITLE
tensorflow==1.12.0 does not exist

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#8]
> pip install tensorflow==1.12.0

```
  Could not find a version that satisfies the requirement tensorflow==1.12.0 (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==1.12.0
```

More info:
> python -V
`Python 3.7.1`

Refer to https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#install-prerequisites-for-running-the-pipeline

**Comment by SenthilCaesar** [comment]
The model works fine in Python 3.6 environment.
When I tested the model in Python 3.7 environment, it produced some numpy shape error in tensor flow module

**Comment by tashrifbillah** [comment]
We found that the stated tensorflow version properly installs with `python==3.6` (see https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation/commit/fdad921373b6a95360fa975394845e55d0b63bd9).
However, `Miniconda3*.sh` installer installs a different minor version of Python 3 other than 3.6. So, the above error occurred.
