### ISSUE TITLE
Differentiate instruction for CPU vs GPU support

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/CNN-Diffusion-MRIBrain-Segmentation#9]
Should it be:

For CPU:

* pip install tensorflow==1.12.0

For GPU:

* pip install tensorflow-gpu==1.12.0
* conda install cudatoolkit=9.0
* conda install cudnn=7.0.5
    

For both:

* conda install -c pnlbwh ants
* pip install keras==2.2.4
* pip install nibabel
* pip install gputil

**Comment by SenthilCaesar** [comment]
Got it . Thank you Tashrif

**Comment by tashrifbillah** [comment]
Fixed by https://github.com/pnlbwh/CNN-Diffusion-MRIBrain-Segmentation/commit/fdad921373b6a95360fa975394845e55d0b63bd9
